"""Deterministic bidirectional mapping between Alexa track tokens and
Music Assistant queue item identifiers.

Token format:  ``ma:<queue_id>:<queue_item_id>``

This is intentionally simple and transparent to aid debugging.
"""

from __future__ import annotations

import logging
from typing import NamedTuple, Optional

logger = logging.getLogger(__name__)

TOKEN_PREFIX = "ma"
TOKEN_SEPARATOR = ":"


class TokenParts(NamedTuple):
    """Parsed components of an EchoWeave track token."""
    queue_id: str
    item_id: str


def encode_token(queue_id: str, item_id: str) -> str:
    """Build a deterministic Alexa track token from MA identifiers.

    >>> encode_token("queue-1", "item-42")
    'ma:queue-1:item-42'
    """
    return f"{TOKEN_PREFIX}{TOKEN_SEPARATOR}{queue_id}{TOKEN_SEPARATOR}{item_id}"


def decode_token(token: str) -> Optional[TokenParts]:
    """Parse a track token back into MA queue/item IDs.

    Returns ``None`` if the token is malformed or does not originate from
    EchoWeave.

    >>> decode_token("ma:queue-1:item-42")
    TokenParts(queue_id='queue-1', item_id='item-42')
    >>> decode_token("invalid-token") is None
    True
    """
    if not token or not token.startswith(TOKEN_PREFIX + TOKEN_SEPARATOR):
        logger.debug("Token does not match EchoWeave format: %s", token)
        return None

    parts = token.split(TOKEN_SEPARATOR, maxsplit=2)
    if len(parts) != 3:
        logger.warning("Malformed token (expected 3 parts): %s", token)
        return None

    return TokenParts(queue_id=parts[1], item_id=parts[2])


def is_echoweave_token(token: str) -> bool:
    """Return ``True`` if *token* was generated by EchoWeave."""
    return decode_token(token) is not None
